const LinkType = Object.freeze({
  BusinessPhone: "business-phone",
  CustomLink: "custom-link",
  Facebook: "facebook",
  GitHub: "github",
  Indeed: "indeed",
  Instagram: "instagram",
  LinkedIn: "linkedin",
  Mobile: "mobile",
  PersonalPhone: "personal-phone",
  Pinterest: "pinterest",
  Reddit: "reddit",
  Signal: "signal",
  Snapchat: "snapchat",
  StackOverflow: "stackoverflow",
  Telegram: "telegram",
  TikTok: "tiktok",
  Tumblr: "tumblr",
  Twitter: "twitter",
  Website: "website",
  WeChat: "wechat",
  WhatsApp: "whatsapp",
  Xing: "xing",
  YouTube: "youtube",
});

module.exports = LinkType;
